image: node:14.17.3

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

pipeline:
  script:
      - npm install
      - npx eslint . --ext .ts
      - npx solhint 'contracts/**/*.sol'
      - npm run build
      - npx hardhat test
  only:
    changes:
      - contracts/*
      - test/*